// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6-zB63n3UugnfOuMa4R49mYM3imI6gGM',
    appId: '1:972889671232:web:48e3d3c284279d050881a5',
    messagingSenderId: '972889671232',
    projectId: 'ccp-oem',
    authDomain: 'ccp-oem.firebaseapp.com',
    storageBucket: 'ccp-oem.firebasestorage.app',
    measurementId: 'G-E2VNKN35SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMGfQHTLmv_aOL02100Le8U0FTpqCsf4',
    appId: '1:972889671232:android:a56c666329db89cd0881a5',
    messagingSenderId: '972889671232',
    projectId: 'ccp-oem',
    storageBucket: 'ccp-oem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwdscm2kCTi1IcDm2LbsJw9vU6nk1lUCY',
    appId: '1:972889671232:ios:8e2aed107a93c6960881a5',
    messagingSenderId: '972889671232',
    projectId: 'ccp-oem',
    storageBucket: 'ccp-oem.firebasestorage.app',
    iosBundleId: 'com.ariespro.civm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6-zB63n3UugnfOuMa4R49mYM3imI6gGM',
    appId: '1:972889671232:web:7bc31c84c71d432d0881a5',
    messagingSenderId: '972889671232',
    projectId: 'ccp-oem',
    authDomain: 'ccp-oem.firebaseapp.com',
    storageBucket: 'ccp-oem.firebasestorage.app',
    measurementId: 'G-GL8YL1LXX6',
  );
}